name: Scan manifest build and release
on:
  push:
    tags:
      - "*" # build on all tags
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest   
    steps:   
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Create release folder
        run: |
          mkdir -p release && ls && rsync -r . --exclude=release --exclude=node_modules --exclude=cdktf.out  --exclude=manifest.json release && ls release
      - name: Create release zip
        run: |
          zip -r platform-status.zip manifest.json release/*  ".github"

 
