name: Scan manifest build and release
on:
  push:
    tags:
      - "*" # build on all tags
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest   
    steps:   
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Create a release zip
        uses: actions/github-script@v6
        with:
          script: |
            mkdir release
            
            const release = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: "${{ github.ref_name }}",
              generate_release_notes: true,
            });

          debug: true
          result-encoding: "json"
 
