name: Tagged Release

# Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
  
env:
  RELEASE_NAME: platform-status.zip

jobs:
  release:
    runs-on: ubuntu-latest   
    steps:   
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Create release folder
        run: |
          mkdir -p release && ls && rsync -r . ".github" --exclude=release --exclude=node_modules --exclude=cdktf.out  --exclude=manifest.json release && ls release
      - name: Create release zip
        run: |
          zip -r $RELEASE_NAME manifest.json release/*  
      - name: debug
        run: |
          ls -lh
      - name: syft
        run: |
            wget "https://github.com/anchore/syft/releases/download/v0.98.0/syft_0.98.0_linux_amd64.tar.gz" -O "/tmp/syft_0.98.0_linux_amd64.tar.gz"
            tar --no-same-owner -xzf "/tmp/syft_0.98.0_linux_amd64.tar.gz"  
            syft ... --catalogers "+sbom-cataloger"
      - name: Upload artefacts
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const release = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: "Release-${{github.run_number}}",
              generate_release_notes: true,
            });
            
            const releaseFile = process.env.RELEASE_NAME;
            
            await github.rest.repos.uploadReleaseAsset({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: release.data.id,
              name: releaseFile,
              data: await fs.readFileSync(releaseFile),
            });
          debug: false
          result-encoding: "json"
